# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bigmonstercai is Learning
email: bigmonstercai@qq.com
description: > # this means to ignore newlines until "baseurl:"
  鼓捣 记录 玩儿
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bigmonstercai.github.io/" # the base hostname & protocol for your site
twitter_username: bigmonstercai
github_username:  bigmonstercai

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter: 'rouge'
  input: GFM

permalink: '/:title/'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
